name: CI/CD

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  backend-deploy:
    runs-on: ubuntu-latest
    steps:
      # SOURCE 단계 - 저장소 Checkout
      - name: Checkout-source code
        uses: actions/checkout@v3

      # Gradle 실행권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      # Spring boot application 빌드
      - name: Build with gradle
        run: ./gradlew clean build

      # docker image 빌드
      - name: Build docker image
        run: docker build -t hyeonsuson/movieham_movie_api .

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # docker hub 퍼블리시
      - name: Publish to docker hub
        run: docker push hyeonsuson/movieham_movie_api

      # WAS 인스턴스 접속 & 애플리케이션 실행
      - name: Connect to WAS & Execute Application
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.WAS_HOST }}
          username: ${{ secrets.WAS_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.WAS_SSH_PORT }}
          script: |
            docker compose -f /opt/docker-compose/movieham_api/docker-compose.yaml stop movie-api
            docker compose -f /opt/docker-compose/movieham_api/docker-compose.yaml rm -f movie-api
            docker compose -f /opt/docker-compose/movieham_api/docker-compose.yaml pull movie-api
            docker compose -f /opt/docker-compose/movieham_api/docker-compose.yaml up -d movie-api